---
abstract: 'HTTP Body Parser'
author:
  - 'Christian Hansen, C<chansen@cpan.org>'
  - 'Sebastian Riedel, C<sri@cpan.org>'
  - 'Andy Grundman, C<andy@hybridized.org>'
  - 'Torsten Raudssus, C<getty@cpan.org>'
build_requires:
  Test::Deep: 0
  Test::More: 0.86
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Body
requires:
  Carp: 0
  File::Temp: 0.14
  HTTP::Headers: 0
  IO::File: 1.14
resources:
  X_mailing_list: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/catalyst-dev
  repository: https://dev.catalystframework.org/repos/Catalyst/trunk/HTTP-Body/
version: 1.12
