---
abstract: 'Read and write a subset of YAML for CPAN Meta files'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
  - 'David Golden <dagolden@cpan.org>'
build_requires:
  File::Spec: 0
  File::Spec::Functions: 0
  Test::More: 0
  vars: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CPAN-Meta-YAML
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
  package:
    - DB
provides:
  CPAN::Meta::YAML:
    file: lib/CPAN/Meta/YAML.pm
    version: 0.003
requires:
  Carp: 0
  Exporter: 0
  Scalar::Util: 0
  perl: 5.004
resources:
  homepage: http://github.com/dagolden/cpan-meta-yaml/tree
  repository: git://github.com/dagolden/cpan-meta-yaml.git
version: 0.003
