--- #YAML:1.0
name:               Parse-CPAN-Meta
version:            1.4401
abstract:           Parse META.yml and META.json CPAN metadata files
author:
    - Adam Kennedy <adamk@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CPAN::Meta::YAML:  0.002
    File::Spec:        0.80
    JSON::PP:          2.27103
    Test::More:        0.47
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
