--- #YAML:1.0
name:               Net-HTTP
version:            6.01
abstract:           Low-level HTTP connection (client)
author:
    - Gisle Aas <gisle@activestate.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Compress::Raw::Zlib:  0
    IO::Compress::Gzip:   0
    IO::Select:           0
    IO::Socket::INET:     0
    perl:                 5.008008
resources:
    MailingList:  mailto:libwww@perl.org
    repository:   http://github.com/gisle/libwww-perl/tree/Net-HTTP/master
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    IO::Socket::SSL:  1.38
